import { useEffect, useRef, useState } from 'react';
import type { SimulationEvent, SimulationState } from '../simulationTypes';

interface ScenarioVoiceAlertsProps {
  state: SimulationState;
}

function voiceMessage(event: SimulationEvent): string | null {
  switch (event.type) {
    case 'accident_activated': return 'Simulated accident reported. Check the updated route.';
    case 'construction_activated': return 'Road construction reported. Demo travel time has been updated.';
    case 'rain_activated': return 'Heavy rain reported near the selected demo roads.';
    case 'flood_activated': return 'Flood warning. The affected road is blocked in this simulation.';
    case 'congestion_activated': return 'Traffic congestion reported. The demo route cost has changed.';
    case 'blockage_activated': return 'Road blockage detected. Follow the updated demo route.';
    case 'route_recalculated': return `Route recalculated. ${event.message}`;
    case 'hospital_reached': return event.message;
    default: return null;
  }
}

function available(): boolean {
  return typeof window !== 'undefined' && 'speechSynthesis' in window && 'SpeechSynthesisUtterance' in window;
}

export function ScenarioVoiceAlerts({ state }: ScenarioVoiceAlertsProps) {
  const [enabled, setEnabled] = useState(false);
  const [notice, setNotice] = useState('Scenario voice alerts are off. Written alerts remain in the event timeline.');
  const supported = available();
  const handledEventCount = useRef(state.events.length);

  useEffect(() => {
    if (state.events.length < handledEventCount.current) handledEventCount.current = 0;
    const newEvents = state.events.slice(handledEventCount.current);
    handledEventCount.current = state.events.length;
    if (!enabled || !supported) return;
    for (const event of newEvents) {
      const message = voiceMessage(event);
      if (message) window.speechSynthesis.speak(new SpeechSynthesisUtterance(message));
    }
    if (newEvents.some((event) => voiceMessage(event))) setNotice('Spoken alert generated by this browser. No emergency system is connected.');
  }, [enabled, state.events, supported]);

  function toggle() {
    if (!supported) {
      setNotice('Speech synthesis is unavailable. Read scenario alerts in the event timeline.');
      return;
    }
    const next = !enabled;
    handledEventCount.current = state.events.length;
    setEnabled(next);
    if (!next) window.speechSynthesis.cancel();
    setNotice(next ? 'Browser voice alerts enabled for new scenario events.' : 'Voice alerts off. Written alerts remain visible.');
  }

  function testVoice() {
    if (!supported) {
      setNotice('Speech synthesis is unavailable. The written timeline remains active.');
      return;
    }
    window.speechSynthesis.cancel();
    window.speechSynthesis.speak(new SpeechSynthesisUtterance('VIALERT simulation demo. Scenario alerts are mock data only.'));
    setNotice('Browser voice test played. No emergency system is connected.');
  }

  return <section className="panel simulation-voice" aria-labelledby="simulation-voice-title">
    <div className="panel-heading-row"><div><span className="eyebrow">Optional driver alert</span><h2 id="simulation-voice-title">Voice alerts</h2></div><span className={`voice-support ${supported ? 'available' : 'unavailable'}`}>{supported ? 'Browser voice' : 'Text only'}</span></div>
    <p className="panel-description">Important simulated incidents can be spoken by the browser. Written event alerts always remain available.</p>
    <div className="voice-actions">
      <button className={`button ${enabled ? 'button-muted' : 'button-primary'}`} type="button" onClick={toggle} aria-pressed={enabled}>{enabled ? 'Voice alerts on' : 'Turn voice on'}</button>
      <button className="button button-secondary" type="button" onClick={testVoice}>Test voice</button>
    </div>
    <p className="voice-notice" role="status" aria-live="polite">{notice}</p>
  </section>;
}
